name: flutter_mtp_picker
description: A Flutter desktop plugin for browsing phone and camera storage over USB MTP using Windows Portable Devices and libmtp.
version: 0.1.2
repository: https://github.com/pratiktimer/flutter_mtp_picker
issue_tracker: https://github.com/pratiktimer/flutter_mtp_picker/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - mtp
  - windows
  - android
  - usb
  - file-picker

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterMtpPickerPluginCApi
      macos:
        pluginClass: FlutterMtpPickerPlugin
